---
layout: base-page
title: About
permalink: /about/
bodyClass: page
nav_items: [concepts, posts, stats, registers]
---
:page-liquid:

The Geolexica for Intelligent transport systems (ITS)
provides concepts from the ISO 14812:2022 standard, originating from the
https://github.com/ISO-TC204/iso14812[GitHub version of iso14812].

// Specifically:

// * English terms and definitions are from published



== Current content ({{ site.data.metadata.version }} edition)

The current contents in the online version of the ISO/TC 204 ITS are
from the
https://github.com/ISO-TC204/iso14812[GitHub version of iso14812]:

* {{ site.data.metadata.concept_count }} English language terminology entries


== Copyright

(C) {{ site.time | date: "%Y" }} International Organization for Standardization.

All rights reserved. Unless otherwise specified, no part of this
site or its documents may be reproduced or utilized otherwise in any form or by any
means, electronic or mechanical, including photocopying, or posting on the
internet or an intranet, without prior written permission. Permission can
be requested from the address below.

[%hardbreaks]
International Organization for Standardization
Chemin de Blandonnet 8
CP 401
1214 Vernier, Geneva
Switzerland
mailto:copyright@iso.org[copyright@iso.org]
https://www.iso.org/[www.iso.org]
